### ISSUE TITLE
Question about input size

### ISSUE THREAD

**Issue by hedjazi** [FacePerceiver/FaRL#7]
Hi, thank you very much for this great work. I see that the input to the CLIP model is of size 224x224, however the parsing and the alignment models' input is 448x448, would you please clarify this? thank you.

**Comment by yinglinzheng** [comment]
Please check our paper for more details, section 4.4.
![图片](https://user-images.githubusercontent.com/89906355/192736384-8ced4234-c20a-4d19-8b14-d416da28c2b4.png)

**Comment by hedjazi** [comment]
@yinglinzheng Thank you, I am sorry I should have read the paper first.
